FROM nginx:alpine

# Copy your local scripts/files into Nginx's default public directory
COPY dist/* /usr/share/nginx/html/
COPY index.html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 to access the web server
EXPOSE 80